# Use Dockerized infrastructure
sudo: false
language: node_js 
node_js:
  - "10"
branches:
  only:
  - master
before_install:
    # Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
    - openssl aes-256-cbc -K $encrypted_052a7cd3d4e4_key -iv $encrypted_052a7cd3d4e4_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
    # If the SDK is not already cached, download it and unpack it
    - tar -xzf credentials.tar.gz
script:
    - npm run lint_js
    - npm run lint_ejs
deploy:
    provider: gae
    skip_cleanup: true
    keyfile: client-secret.json
    project: scioly-apps
    default: true
