sudo: false
language: node_js
node_js:
- node
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_97cee6e1dded_key -iv $encrypted_97cee6e1dded_iv
-in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
script:
- npm run lint_js
- npm run lint_ejs
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: scioly-apps
  default: true
