runtime: nodejs10
beta_settings:
  cloud_sql_instances: scioly-apps:us-central1:apps
env_variables:
  INSTANCE_CONNECTION_NAME: scioly-apps:us-central1:apps
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
